apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: op-node
  labels:
    app: op-node
spec:
  serviceName: op-node
  replicas: 1
  selector:
    matchLabels:
      app: op-node
  template:
    metadata:
      labels:
        app: op-node
    spec:
      restartPolicy: Always
      containers:
        - name: op-node
          image: us-central1-docker.pkg.dev/bedrock-goerli-development/images/op-node
          imagePullPolicy: Always
          command:
            - op-node
          env:
            - name: OP_NODE_L2_ENGINE_RPC
              value: ws://op-geth:8551
            - name: OP_NODE_L2_ETH_RPC
              value: ws://op-geth:8546
          envFrom:
            - configMapRef:
                name: op-node-env
          volumeMounts:
            - mountPath: /etc/op-node
              name: op-node-config
          ports:
            - containerPort: 9003
              name: p2p
            - containerPort: 9545
              name: rpc
            - containerPort: 7300
              name: metrics
          livenessProbe:
            httpGet:
              port: rpc
              path: /healthz
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              port: rpc
              path: /healthz
            initialDelaySeconds: 60
      volumes:
        - name: op-node-config
          configMap:
            name: op-node-config
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: op-geth
  labels:
    app: op-geth
spec:
  serviceName: op-geth
  replicas: 1
  selector:
    matchLabels:
      app: op-geth
  template:
    metadata:
      labels:
        app: op-geth
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
        - name: op-geth
          image: ethereumoptimism/op-geth
          imagePullPolicy: Always
          command:
            - sh
            - /etc/op-geth-scripts/entrypoint.sh
          envFrom:
            - configMapRef:
                name: op-geth-env
          volumeMounts:
            - mountPath: /etc/op-geth
              name: op-geth-config
            - mountPath: /etc/op-geth-scripts
              name: op-geth-scripts
            - mountPath: /db
              name: datadir
          ports:
            - containerPort: 8545
              name: rpc
            - containerPort: 8546
              name: ws
            - containerPort: 8551
              name: engine
          livenessProbe:
            exec:
              command:
                - sh
                - /etc/op-geth-scripts/liveness-probe.sh
                - geth
          resources:
            requests:
              cpu: "4"
              memory: 8Gi
            limits:
              cpu: "4"
              memory: 8Gi
      volumes:
        - name: op-geth-config
          configMap:
            name: op-geth-config
        - name: op-geth-scripts
          configMap:
            name: op-geth-scripts
        - name: datadir
          persistentVolumeClaim:
            claimName: op-geth-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacy-geth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legacy-geth
  template:
    spec:
      terminationGracePeriodSeconds: 600
      restartPolicy: Always
      containers:
        - name: l2geth-replica
          image: ethereumoptimism/l2geth
          command:
            - sh /legacy-geth-scripts/entrypoint.sh
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8545
              protocol: TCP
            - containerPort: 8546
              protocol: TCP
          resources:
            limits:
              cpu: "4"
              memory: 16Gi
            requests:
              cpu: "4"
              memory: 16Gi
          envFrom:
            - configMapRef:
                name: legacy-geth-env
          volumeMounts:
            - name: legacy-geth-data
              mountPath: /db
            - name: legacy-geth-scripts
              mountPath: /legacy-geth-scripts
          livenessProbe:
            exec:
              command:
                - /script/liveliness/test.sh
                - geth
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: legacy-geth-data
        - name: geth-scripts
          configMap:
            name: legacy-geth-scripts
            defaultMode: 0777