apiVersion: v1
kind: Service
metadata:
  name: op-node
  labels:
    app: op-node
spec:
  type: NodePort
  selector:
    app: op-node
  ports:
    - port: 9545
      name: rpc
    # include the P2P port here too in case we want to peer
    # with other pods within the cluster
    - port: 9003
      name: p2p
    - port: 7300
      name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: op-geth
  labels:
    app: op-geth
spec:
  type: NodePort
  selector:
    app: op-geth
  ports:
    - port: 8545
      name: rpc
    - port: 8546
      name: ws
    - port: 8551
      name: engine
---
apiVersion: v1
kind: Service
metadata:
  name: legacy-geth
  labels:
    app: legacy-geth
spec:
  type: NodePort
  selector:
    app: op-geth
  ports:
    - port: 8545
      name: rpc
    - port: 8546
      name: ws